[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "alphagrowth-visualizer/frontend"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_FLAGS = "--legacy-peer-deps --no-audit"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 